apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jtxht1d22-go
  janus-idp.io/tekton: jtxht1d22-go
  backstage.io/kubernetes-id: jtxht1d22-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jtxht1d22-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
